# Generated by Django 5.1.6 on 2025-03-03 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='passenger',
        ),
        migrations.AddField(
            model_name='reservation',
            name='passenger',
            field=models.ManyToManyField(to='reservations.passenger'),
        ),
    ]
