# Generated by Django 5.1.6 on 2025-03-03 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_remove_reservation_passenger_reservation_passenger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='seat_number',
            field=models.CharField(max_length=25),
        ),
    ]
